name: miglionico_mobile
description: "A new Flutter project for exploring Miglionico."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  webview_flutter: ^3.0.0
  font_awesome_flutter: ^10.4.0
  animated_text_kit: ^4.2.2
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^5.0.0
  provider: ^6.1.2 # Versione suggerita di provider
  http: ^1.0.0
  shared_preferences: ^2.1.0
  url_launcher: ^6.1.7



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0



flutter:
  uses-material-design: true






